version: '3.8'

services:
  zigbeemqttexporter:
    image: revenberg/zigbeemqttexporter
    container_name: zigbeemqttexporter
    restart: always
    ports:
      - 9004:9004
    expose:
      - 9004
    environment:
      - MQTT_ADDRESS=192.168.2.80
      - MQTT_TOPIC=zigbee2mqtt/#
      - MQTT_IGNORED_TOPICS=bridge
      - PROMETHEUS_PREFIX=reading_
      - TOPIC_LABEL=reading
      - LOG_LEVEL=DEBUG      
    